name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/deployment/flask_app/Dockerfile
          push: true
          tags: dicksonml/realestate-api:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name test_api dicksonml/realestate-api:latest
          sleep 10  # wait for Flask to start

      - name: Install dependencies
        run: pip install requests pytest

      - name: Run API tests
        run: pytest tests/ --disable-warnings -q

      - name: Stop container
        run: docker stop test_api && docker rm test_api
